# Generated by Django 3.1.13 on 2025-09-27 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
        ('teacher', '0002_teacher_salary'),
        ('student', '0004_student_enrollment_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_file', models.FileField(blank=True, null=True, upload_to='theory_papers/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checked', 'Checked')], default='pending', max_length=20)),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
