# Generated by Django 3.0.5 on 2025-09-28 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papersubmission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theorypaper',
            name='marks',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
