# Generated by Django 3.0.5 on 2025-09-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofilerequest',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofilerequest',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
