# Generated by Django 3.0.5 on 2025-10-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_enrollment_number'),
        ('studentprofile', '0002_auto_20250928_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
