# Generated by Django 3.0.5 on 2025-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0003_paper_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='paper',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='excels/'),
        ),
    ]
