# Generated by Django 3.0.5 on 2025-11-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_enrollment_number'),
        ('studentprofile', '0004_auto_20251111_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='selected_students',
            field=models.ManyToManyField(blank=True, related_name='selected_papers', to='student.Student'),
        ),
    ]
