# Generated by Django 3.0.5 on 2025-11-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_enrollment_number'),
        ('studentprofile', '0005_paper_selected_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_file',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
        migrations.CreateModel(
            name='StudentPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_file', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentprofile.Paper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
