# Generated by Django 3.0.5 on 2025-11-20 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
        ('studentprofile', '0006_auto_20251120_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilerequest',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Course'),
        ),
    ]
