# Generated by Django 3.1.13 on 2025-09-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
